### ISSUE TITLE
`win_options` will not work from second time

### ISSUE THREAD

**Issue by ghost** [rhysd/electron-about-window#33] opened 2018-11-06 07:10 UTC
About-window version: ^1.12.1(install from npmjs.com)
ElectronJS Version: ^3.0.7
OS: macOS Mojave 10.14.2

Details  in Codes

```
const aboutWindowInfo = {
  icon_path: path.join(__dirname, '/assets/icon.png'),
  open_devtools: false,
  use_version_info: false,
  win_options: {titleBarStyle: 'hidden', minimizable: false, movable: false, resizable: false,maximizable: false}
}
```

```
{
    label: `About this app`,
    click: () => openAboutWindow(aboutWindowInfo)
}
```

When run this app and click the menu `About this app` for first time, the `win_options` will work well

![screen shot 2018-11-06 at 3 05 36 pm](https://user-images.githubusercontent.com/44664943/48048209-b1ad2c00-e1d5-11e8-881e-b417f6373531.png)

But from the second, each time I click the menu `About this app`, the `win_options` will not work

![screen shot 2018-11-06 at 3 05 49 pm](https://user-images.githubusercontent.com/44664943/48048248-dc978000-e1d5-11e8-962f-b216c0b2bfe3.png)

This window has titleBar, and it can be moved, resized and more.

**Comment by tsvetilian-ty** [comment] 2018-11-07 10:36
@h9 I was not able to reproduce the problem you talk about under Windows, can you try to clone this repo > run ``npm install`` > change main.js in example directory (win_options) > run ``npm start debug``

**Comment by h9** [comment] 2018-11-08 13:12
@tsvetilian-ty  thanks for the reply, I did as you asked on Mac, it works well, but in my project that uses this package, still can show that bug. Please look at following link that I take a record for you.

https://www.dropbox.com/s/00jxqqkqc5rcldk/Screen%20Recording%202018-11-08%20at%209.09.31%20PM.mov?dl=0

It's so strange.

**Comment by tsvetilian-ty** [comment] 2018-11-08 14:32
@h9 it looks like the about windows is going to it's default state. Can you try to pass the AboutWindowInfo  object directly ?
```javascript
{
    label: `About this app`,
    click: () => openAboutWindow({
                     icon_path: path.join(__dirname, '/assets/icon.png'),
                     open_devtools: false,
                     use_version_info: false,
                     win_options: {titleBarStyle: 'hidden', minimizable: false, movable: false, resizable: false,maximizable: false}
    })
}
```

**Comment by h9** [comment] 2018-11-08 14:44
@tsvetilian-ty I tried, but still the same.

**Comment by bampakoa** [comment] 2019-05-16 12:34
I have the same exact problem in Windows 10. [Here](https://gist.github.com/75713bbc4571c0aff4deb44c7c26a2e4) is a gist, to use with [Electron Fiddle](https://electronjs.org/fiddle), that showcases the actual problem. Thanks!

**Comment by bampakoa** [comment] 2019-10-30 12:58
@ghost Until the #49 is merged you can try to pass a clone of your options object such as:

```

const options = {
 ....
}
openAboutWindow({...options});
```

**Closed** 2019-11-03 13:58 UTC
